### ISSUE TITLE
Publish as python package

### ISSUE THREAD

**Issue by clbarnes** [jakubcerveny/gilbert#1]
Would you be interested in this becoming an installable library on pypi.org so that others could easily use it? I am happy to do the work but thought I'd see whether it would be welcome before just raising a massive PR. Alternatively if it would distract too much from the core algorithm I'm happy to make a separate package which just refers back to this.

**Comment by jakubcerveny** [comment]
Hi Chris, thanks for the offer but I'm not sure this is actually a library. This is just an algorithm that I thought could be useful to someone and I chose Python to publish it, more or less as "pseudocode" (the original version was in C++). How massive would the packaging be? Just linking from a separate package actually sounds good. It would leave this repo as a simple reference for the original (naive) algorithm and the production version (possibly optimized or non-recursive) could have its own repo (I'll be happy to link to your work).

**Comment by clbarnes** [comment]
I am personally a fan of small libraries with a lot of build cruft so it sounds like a separate project may be the way to go! I'll let you know if/when I get round to it.
