### ISSUE TITLE
C implementation returns 0, 0 as an index for larger dimensions.

### ISSUE THREAD

**Issue by OetkenPurveyorOfCode** [jakubcerveny/gilbert#11]
I think it is because of this line.
line 187 in gilbert.c
```
if (max_iter > 100000) { return -1; }
```
When this line is removed, the `gilbert_d2xy` appears to wrok fine with larger width and height. Otherwise it returns 0. As an example
`gilbert_d2xy(&x, &y, 7861, 490, 490)` sets x and y incorrectly to zero and returns -1. 
Can you explain why you set a maxiter value in the c implementation, when it works fine beyond that?
(I know it is correct to guard against things like overflow, but dimensions like 490x490 are not that large and uncommon and overflow still does not seem to happen at these still relatively small width and height values)

**Comment by grendell** [comment]
I should have checked the existing issues before creating [my own demo](https://github.com/grendell/gilbert-c-walk). XD

Thanks for tracking down the `max_iter` check!

**Comment by grendell** [comment]
@abetusk could you confirm the proposed fix?

**Comment by abetusk** [comment]
Yes, my apologies, this was my stupidity. I think this was a fail safe while testing to make sure I didn't blow things up but I forgot to remove it after testing was done.

Unless someone beats me to it, I'll put in a PR with this fix and add a test to make sure.

**Comment by abetusk** [comment]
PR submitted. Sorry for the noise, folks.

**Comment by grendell** [comment]
No worries, thanks for the fix and especially the port!
