### ISSUE TITLE
I used gilbert in a video series

### ISSUE THREAD

**Issue by clawsoon** [jakubcerveny/gilbert#5]
This is not an issue report, just letting you know that all the questions I asked you months ago have finally turned into something.  I used a gilbert curve as a chromosome map in this very long (5 part, 42 hour) video series:

https://www.youtube.com/watch?v=6Ev2WgLk9Oc&list=PL0elTBjXjW_52wz-JBuRfFQIgrRUfONWR

It might not be your kind of thing, but I just wanted to say thanks for the code!

**Comment by jakubcerveny** [comment]
Thanks for sharing! I love seeing where the code ends up, like this fascinating application. I just wish there were more introductory notes in the description -- I must admit I don't fully understand the meaning of the visualization. Anyway, thanks for letting me know.

**Comment by clawsoon** [comment]
I had vague plans to put more explanatory comments into it, but I ran out of steam and realized that if I didn't publish it now I'd probably never get it done.  So your lack of understanding is a victim of my laziness.  :-)
