### ISSUE TITLE
Closed form

### ISSUE THREAD

**Issue by DarkWingMcQuack** [jakubcerveny/gilbert#6]
Hey i just wanted to know if there was any research been done in achieving a closed form for this curve.
Is there a way to calculate the discrete value `f(x)` for a cell `x` in `O(1)`?

**Comment by jakubcerveny** [comment]
I was thinking of adding mapping functions similar to `xy2d` and `d2xy` from https://en.wikipedia.org/wiki/Hilbert_curve (but didn't have time for that yet). Those however seem to work in `O(logN)` where `N` is the width of the domain. Do you have an example for the classic Hilbert curve that works in `O(1)`?

**Comment by DarkWingMcQuack** [comment]
I dont have a `O(1)` but i thought maybe the more general form of the curve presented in this repository maybe makes it possible to optimize it further.
I havent thought about it much, just thought i would ask first :)
